version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm update -g npm
  pre_build:
    commands:
      - pwd
      - npm i
      - bash ./createenv.sh
  build:
    commands:
      - npm run build
artifacts:
  files:
    - ./**/*
